### ISSUE TITLE
ENV file

### ISSUE THREAD

**Issue by creeper6530** [afazio1/robotic-nation-proj#3]
I think for Discord bots it'll be better to use .env file to store the token. For example, if someone is going to host the script on some service, it'll be much safer to protect yourself from being hacked.

In Python, you can read .env file using this syntax:
`token = os.getenv(VARIABLE_NAME)`
And .env file in same directory as Python script is going to be formatted like this:
`VARIABLE_NAME=your_token_here`

P.S.: Sorry for eventual mistakes in English

**Comment by afazio1** [comment]
Hi @creeper6530, thank you for this feedback! This helps a lot. I recently added comments in the scripts explaining how to setup .env files. By the way, your English is excellent!

**Comment by creeper6530** [comment]
By the way, don't forget to import os module!
